sudo: required

language: ruby

services:
  - docker

install: true

before_script:
  - cp .env.travis .env
  - sudo /etc/init.d/postgresql stop
  - docker-compose build

script:
  - docker-compose run baasile_io rspec
