sudo: required

language: ruby

services:
  - docker

# skip installation step (tests run into docker containers)
install: true

# prepare environment variables
# stop postgres default travis service
# build app and setup database
before_script:
  - cp .env.travis .env
  - sudo /etc/init.d/postgresql stop
  - docker-compose -f docker-compose-test.yml build
  - docker-compose -f docker-compose-test.yml up -d postgres
  - sleep 10
  - docker-compose -f docker-compose-test.yml run baasile_io_test rails db:setup

# run tests
script:
  - docker-compose -f docker-compose-test.yml run baasile_io_test rspec
