version: '2'

networks:
  baasile_io_network:
    driver: 'bridge'

services:
  postgres:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    networks:
      - 'baasile_io_network'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.0'
    command: 'redis-server'
    ports:
      - '6379:6379'
    networks:
      - 'baasile_io_network'
    depends_on:
      - 'postgres'
    volumes:
      - 'redis:/var/lib/redis/data'

  selenium:
    image: selenium/standalone-firefox
    container_name: selenium
    ports:
      - '4444:4444'
    networks:
      - 'baasile_io_network'

  baasile_io:
    build: '.'
    command: ["./scripts/wait_for_postgres.sh", "postgres", "--", "bundle", "exec", "rails", "s", "-p", "3042", "-b", "0.0.0.0"]
    volumes:
      - '.:/baasile_io'
    env_file:
      - '.env'
    ports:
      - '3042:3042'
    networks:
      - 'baasile_io_network'
    depends_on:
      - 'redis'
      - 'selenium'

  sidekiq:
    build: '.'
    command: 'bundle exec sidekiq -c 1 -q default -q mailers'
    volumes:
      - '.:/baasile_io'
    env_file:
      - '.env'
    networks:
      - 'baasile_io_network'
    depends_on:
      - 'baasile_io'

volumes:
  redis:
  postgres:
