default: &default
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000
  schema_search_path: "public,hstore,trgm"

development:
  <<: *default
  port: 5432
  host: postgres
  database: baasile_io_development
  username: postgres
  password:
